# Generated by Django 5.0.4 on 2024-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("about", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("IT", "IT"), ("NON IT", "NON IT"), ("RPA", "RPA")],
                        max_length=100,
                    ),
                ),
                ("added_date", models.DateField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
